version: "3.8"
services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - ./back-end:/app
    ports:
      - "5000:5000"
    # command: ["node", "src/index.js"]
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - ./front-end:/app
    ports:
      - "3000:3000"
    # command: ["npm","run","serve:start"]
